---
# Source: tempo-distributed/templates/poddisruptionbudget/ingester.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tempo-distributed-ingester
  namespace: obskit
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: ingester
    app.kubernetes.io/part-of: memberlist
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo-distributed
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/component: ingester
