apiVersion: v1
kind: Service
metadata:
  name: agent
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent
  ports:
    - name: http-metrics
      port: 80
      targetPort: 80
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
