apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-distributed
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
automountServiceAccountToken: true
