---
# Source: loki-distributed/templates/poddisruptionbudget/query-scheduler.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-distributed-query-scheduler
  namespace: obskit
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: query-scheduler
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki-distributed
      app.kubernetes.io/instance: loki
      app.kubernetes.io/component: query-scheduler
