---
# Source: tempo-distributed/templates/servicemonitor/jaeger-query.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tempo-distributed-tempo-query
  namespace: obskit
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: tempo-query
spec:
  endpoints:
    - port: http-metrics
      relabelings:
        - sourceLabels: [job]
          replacement: "obskit/tempo-query"
          targetLabel: job
      scheme: http
  namespaceSelector:
    matchNames:
    - obskit
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo-distributed
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/component: tempo-query
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
