apiVersion: v1
kind: Service
metadata:
  name: loki-distributed-compactor
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: compactor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: compactor
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
