apiVersion: v1
kind: Service
metadata:
  name: loki-distributed-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: gateway
spec:
  type: {{ ternary "ClusterIP" "LoadBalancer" (eq .Values.ingress.enable true) }}
  selector:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
