---
# Source: mimir-distributed/templates/persistentvolumeclaim/ingester.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimir-distributed-ingester-zone-a
  namespace: obskit
spec:
  storageClassName: mimir-distributed-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
# Source: mimir-distributed/templates/persistentvolumeclaim/ingester.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimir-distributed-ingester-zone-b
  namespace: obskit
spec:
  storageClassName: mimir-distributed-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
# Source: mimir-distributed/templates/persistentvolumeclaim/ingester.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimir-distributed-ingester-zone-c
  namespace: obskit
spec:
  storageClassName: mimir-distributed-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
