---
# Source: loki-distributed/templates/storageclass/loki.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki-distributed-storageclass
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
  replication-type: regional-pd
volumeBindingMode: WaitForFirstConsumer
