---
# Source: tempo-distributed/templates/configmap/default.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-distributed-config
  namespace: obskit
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
data:
  tempo-query.yaml: |
    backend: 127.0.0.1:3100
  overrides.yaml: |
    overrides: {}
  config.yaml: |
    compactor:
      compaction:
        block_retention: 48h
        chunk_size_bytes: 5242880
        compacted_block_retention: 1h
        compaction_cycle: 30s
        compaction_window: 1h
        flush_size_bytes: 20971520
        iterator_buffer_size: 1000
        max_block_bytes: 107374182400
        max_compaction_objects: 6000000
        max_time_per_tenant: 5m
        retention_concurrency: 10
      ring:
        kvstore:
          store: memberlist

    distributor:
      # receivers: null
      ring:
        kvstore:
          store: memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 3
        tokens_file_path: /var/tempo/tokens.json

    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
      - tempo-distributed-gossip-ring

    metrics_generator_enabled: false

    multitenancy_enabled: false

    overrides:
      per_tenant_override_config: /conf/overrides.yaml

    querier:
      frontend_worker:
        frontend_address: tempo-distributed-query-frontend-discovery:9095

    search_enabled: true

    server:
      grpc_server_max_recv_msg_size: 4194304
      grpc_server_max_send_msg_size: 4194304
      http_listen_port: 3100
      log_format: logfmt
      log_level: debug

    storage:
      trace:
        backend: s3
        blocklist_poll: 5m
        cache: memcached
        local:
          path: /var/tempo/traces
        memcached:
          consistent_hash: true
          host: tempo-distributed-memcached
          service: memcached-client
          timeout: 500ms
        s3:
          bucket: <BUCKET_NAME>
          endpoint: <ENDPOINT>
          access_key: <ACCES_KEY>
          secret_key: <SECRET_ACCES_KEY>
          insecure: true
        wal:
          path: /var/tempo/wal
