apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap/default.yaml
- configmap/gateway.yaml
- serviceaccount/tempo.yaml
{{ if eq .Values.persistence true }}
- storageclass/tempo.yaml
- persistentvolumeclaim/compactor.yaml
- persistentvolumeclaim/ingester.yaml
{{ end }}
- service/gossip-ring.yaml
- service/memcached.yaml
- statefulset/memcached.yaml
- poddisruptionbudget/ingester.yaml
- service/ingester-discovery.yaml
- service/ingester.yaml
- statefulset/ingester.yaml
- service/distributor-discovery.yaml
- service/distributor.yaml
- deployment/distributor.yaml
- service/compactor.yaml
- deployment/compactor.yaml
- service/querier.yaml
- deployment/querier.yaml
- service/query-frontend-discovery.yaml
- service/query-frontend.yaml
- deployment/query-frontend.yaml
- service/gateway.yaml
- deployment/gateway.yaml
{{ if eq .Values.ingress.enable true }}
- secret/gateway-tls.yaml
- ingress/gateway.yaml
{{ end }}
{{ if eq .Values.selfmonitor true }}
- servicemonitor/memcached.yaml
- servicemonitor/ingester.yaml
- servicemonitor/distributor.yaml
- servicemonitor/compactor.yaml
- servicemonitor/querier.yaml
- servicemonitor/jaeger-query.yaml
- servicemonitor/query-frontend.yaml
{{ end }}
{{ if eq .Values.autoscaling true }}
- horizontalpodautoscaler/ingester.yaml
- horizontalpodautoscaler/distributor.yaml
- horizontalpodautoscaler/querier.yaml
- horizontalpodautoscaler/query-frontend.yaml
- horizontalpodautoscaler/gateway.yaml
{{ end }}
