---
# Source: loki-distributed/templates/service/gateway.yaml
apiVersion: v1
kind: Service
metadata:
  name: loki-distributed-gateway
  namespace: obskit
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: gateway
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
