---
# Source: loki-distributed/templates/service/ingester.yaml
apiVersion: v1
kind: Service
metadata:
  name: loki-distributed-ingester
  namespace: obskit
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: ingester
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: ingester
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
