---
# Source: loki-distributed/templates/service/memcached-chunks.yaml
apiVersion: v1
kind: Service
metadata:
  name: loki-distributed-memcached-chunks
  namespace: obskit
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: memcached-chunks
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: memcached-chunks
  ports:
    - name: memcached-client
      port: 11211
      targetPort: http
      protocol: TCP
    - name: http-metrics
      port: 9150
      targetPort: http-metrics
      protocol: TCP
