apiVersion: v1
kind: Service
metadata:
  name: loki-distributed-memberlist
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/part-of: memberlist
  ports:
    - name: tcp
      port: 7946
      targetPort: http-memberlist
      protocol: TCP
