apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tempo-distributed-ingester
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: ingester
spec:
  minReplicas: 1
  maxReplicas:  {{ .Values.ingester.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: tempo-distributed-ingester
