apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent
