---
# Source: mimir-distributed/templates/service/chunks-cache-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: mimir-distributed-chunks-cache-headless
  namespace: obskit
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: chunks-cache
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: chunks-cache
  ports:
    - name: memcached-client
      port: 11211
      targetPort: 11211
    - name: http-metrics
      port: 9150
      targetPort: 9150
