---
# Source: mimir-distributed/templates/service/ingester-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: mimir-distributed-ingester-headless
  namespace: obskit
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: ingester
    app.kubernetes.io/part-of: memberlist
    # prometheus.io/service-monitor: "false"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: ingester
  ports:
    - port: 9095
      protocol: TCP
      name: grpc
      targetPort: grpc
