---
# Source: grafana/templates/clusterrole/grafana.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-clusterrole
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
