apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
spec:
  type: {{ ternary "ClusterIP" "LoadBalancer" (eq .Values.ingress.enable true) }}
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
