---
# Source: grafana-agent/templates/serviceaccount/grafana-agent.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: default
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent
