---
# Source: loki-distributed/templates/serviceaccount/loki.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-distributed
  namespace: obskit
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
automountServiceAccountToken: true
