apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-distributed-runtime
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
data:
  runtime.yaml: |
    {}
