---
# Source: tempo-distributed/templates/service/compactor.yaml
apiVersion: v1
kind: Service
metadata:
  name: tempo-distributed-compactor
  namespace: obskit
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: compactor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: compactor
  ports:
    - name: http-metrics
      port: 3100
      targetPort: 3100
      protocol: TCP
