---
# Source: tempo-distributed/templates/service/query-frontend.yaml
apiVersion: v1
kind: Service
metadata:
  name: tempo-distributed-query-frontend
  namespace: obskit
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: query-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: query-frontend
  ports:
    - name: http-metrics
      port: 3100
      targetPort: 3100
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
