apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-distributed-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: gateway
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo-distributed
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo-distributed
        app.kubernetes.io/instance: tempo
        app.kubernetes.io/component: gateway
    spec:
{{ if eq .Values.minikube false }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: tempo-distributed
                  app.kubernetes.io/instance: tempo
                  app.kubernetes.io/component: gateway
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: tempo-distributed
                    app.kubernetes.io/instance: tempo
                    app.kubernetes.io/component: gateway
                topologyKey: topology.kubernetes.io/zone
{{ end }}
      enableServiceLinks: false
      serviceAccountName: tempo-distributed
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: tempo-distributed
              app.kubernetes.io/instance: tempo
              app.kubernetes.io/component: gateway
      volumes:
        - name: config
          configMap:
            name: tempo-distributed-gateway
        - name: temp
          emptyDir: {}
        - name: docker-entrypoint-d-override
          emptyDir: {}
      containers:
        - name: nginx
          image: "docker.io/nginxinc/nginx-unprivileged:1.19-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http-metrics
            initialDelaySeconds: 15
            timeoutSeconds: 1
{{ if eq .Values.setresources true }}
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi
{{ end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: config
              mountPath: /etc/nginx
            - name: temp
              mountPath: /tmp
            - name: docker-entrypoint-d-override
              mountPath: /docker-entrypoint.d
