apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-distributed-query-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: query-frontend
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo-distributed
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/component: query-frontend
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo-distributed
        app.kubernetes.io/instance: tempo
        app.kubernetes.io/component: query-frontend
    spec:
{{ if eq .Values.minikube false }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: tempo-distributed
                  app.kubernetes.io/instance: tempo
                  app.kubernetes.io/component: query-frontend
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: tempo-distributed
                    app.kubernetes.io/instance: tempo
                    app.kubernetes.io/component: query-frontend
                topologyKey: topology.kubernetes.io/zone
{{ end }}
      enableServiceLinks: false
      serviceAccountName: tempo-distributed
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: tempo-distributed
              app.kubernetes.io/instance: tempo
              app.kubernetes.io/component: query-frontend
      volumes:
        - name: config
          configMap:
            name: tempo-distributed-config
        - name: data
          emptyDir: {}
      containers:
        - name: query-frontend
          image: docker.io/grafana/tempo:1.5.0
          imagePullPolicy: IfNotPresent
          args:
            - -target=query-frontend
            - -config.file=/conf/config.yaml
            - -mem-ballast-size-mbs=1024
          ports:
            - containerPort: 3100
              name: http-metrics
            - containerPort: 9095
              name: grpc
{{ if eq .Values.setresources true }}
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 2
              memory: 4Gi
{{ end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /conf
              name: config
            - mountPath: /var/tempo
              name: data
