apiVersion: v1
kind: Secret
metadata:
  name: agent
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent
stringData:
  config.yaml: |
    server:
      log_level: {{ .Values.server.log_level }}
      log_format: {{ .Values.server.log_format }}

    logs:
      configs:
      - name: default
        clients:
          - url: {{ .Values.remotes.loki.url }}
        positions:
          filename: /tmp/positions.yaml
        scrape_configs:
          - job_name: kubernetes-pods
            pipeline_stages:
              # - cri: {}
              - drop:
                  expression: "(.*/health-check.*)|(.*/health.*)"
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                regex: agent
                action: drop
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                regex: agent-config-reloader
                action: drop
              - source_labels:
                  - __meta_kubernetes_pod_controller_name
                target_label: __tmp_controller_name
                regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                action: replace
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_name
                  - __meta_kubernetes_pod_label_app
                  - __tmp_controller_name
                  - __meta_kubernetes_pod_name
                target_label: app
                regex: ^;*([^;]+)(;.*)?$
                action: replace
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                  - __meta_kubernetes_pod_label_release
                target_label: instance
                regex: ^;*([^;]+)(;.*)?$
                action: replace
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_component
                  - __meta_kubernetes_pod_label_component
                target_label: component
                regex: ^;*([^;]+)(;.*)?$
                action: replace
              - source_labels:
                  - __meta_kubernetes_pod_node_name
                target_label: node_name
                action: replace
              - source_labels:
                  - __meta_kubernetes_namespace
                target_label: namespace
                action: replace
              - source_labels:
                  - namespace
                  - app
                target_label: job
                separator: /
                action: replace
                replacement: $1
              - source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
                action: replace
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                target_label: container
                action: replace
              - source_labels:
                  - __meta_kubernetes_pod_uid
                  - __meta_kubernetes_pod_container_name
                target_label: __path__
                separator: /
                action: replace
                replacement: /var/log/pods/*$1/*.log
              - source_labels:
                  - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
                  - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
                  - __meta_kubernetes_pod_container_name
                target_label: __path__
                separator: /
                regex: true/(.*)
                action: replace
                replacement: /var/log/pods/*$1/*.log

    metrics:
      wal_directory: /tmp/agent/wal
      global:
        scrape_interval: {{ .Values.metrics.global.scrape_interval }}
        external_labels:
          cluster: {{ .Values.cluster_name }}
        remote_write:
          - url: {{ .Values.remotes.mimir.url }}
      configs:
      - name: default
        remote_write:
        - url: {{ .Values.remotes.mimir.url }}

    integrations:
      metrics:
        autoscrape:
          enable: true
          metrics_instance: default
      node_exporter:
        rootfs_path: /host/root
        sysfs_path: /host/sys
        procfs_path: /host/proc

    traces:
      configs:
      - name: default
        remote_write:
          - endpoint: {{ .Values.remotes.tempo.endpoint }}
            insecure:  {{ .Values.remotes.tempo.insecure }}
            protocol: http
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: 0.0.0.0:4317
