apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-distributed-compactor
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: loki-distributed-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
