---
# Source: mimir-distributed/templates/statefulset/compactor.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir-distributed-compactor
  namespace: obskit
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: compactor
    app.kubernetes.io/part-of: memberlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir-distributed
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/component: compactor
  updateStrategy:
    type: RollingUpdate
  serviceName: mimir-distributed-compactor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir-distributed
        app.kubernetes.io/instance: mimir
        app.kubernetes.io/component: compactor
        app.kubernetes.io/part-of: memberlist
    spec:
      serviceAccountName: mimir-distributed
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: mimir-distributed
              app.kubernetes.io/instance: mimir
              app.kubernetes.io/component: compactor
      terminationGracePeriodSeconds: 240
      volumes:
        - name: config
          configMap:
            name: mimir-distributed-config
        - name: runtime-config
          configMap:
            name: mimir-distributed-runtime
        - name: data

          emptyDir: {}

        - name: active-queries
          emptyDir: {}
      containers:
        - name: compactor
          image: "grafana/mimir:2.5.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-target=compactor"
            - "-config.expand-env=true"
            - "-config.file=/etc/mimir/config.yaml"
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: memberlist
              containerPort: 7946
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 60

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: config
              mountPath: /etc/mimir
            - name: runtime-config
              mountPath: /var/mimir
            - name: data
              mountPath: "/data"
            - name: active-queries
              mountPath: /active-query-tracker
