---
# Source: tempo-distributed/templates/deployment/gateway.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-distributed-gateway
  namespace: obskit
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: gateway
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo-distributed
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo-distributed
        app.kubernetes.io/instance: tempo
        app.kubernetes.io/component: gateway
    spec:

      enableServiceLinks: false
      serviceAccountName: tempo-distributed
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: tempo-distributed
              app.kubernetes.io/instance: tempo
              app.kubernetes.io/component: gateway
      volumes:
        - name: config
          configMap:
            name: tempo-distributed-gateway
        - name: temp
          emptyDir: {}
        - name: docker-entrypoint-d-override
          emptyDir: {}
      containers:
        - name: nginx
          image: "docker.io/nginxinc/nginx-unprivileged:1.19-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http-metrics
            initialDelaySeconds: 15
            timeoutSeconds: 1

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: config
              mountPath: /etc/nginx
            - name: temp
              mountPath: /tmp
            - name: docker-entrypoint-d-override
              mountPath: /docker-entrypoint.d
