---
# Source: tempo-distributed/templates/deployment/querier.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-distributed-querier
  namespace: obskit
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: querier
    app.kubernetes.io/part-of: memberlist
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo-distributed
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/component: querier
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo-distributed
        app.kubernetes.io/instance: tempo
        app.kubernetes.io/component: querier
        app.kubernetes.io/part-of: memberlist
    spec:

      enableServiceLinks: false
      serviceAccountName: tempo-distributed
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: tempo-distributed
              app.kubernetes.io/instance: tempo
              app.kubernetes.io/component: querier
      volumes:
        - name: config
          configMap:
            name: tempo-distributed-config
        - name: data
          emptyDir: {}
      containers:
        - name: querier
          image: docker.io/grafana/tempo:1.5.0
          imagePullPolicy: IfNotPresent
          args:
            - -target=querier
            - -config.file=/conf/config.yaml
            - -mem-ballast-size-mbs=1024
          ports:
            - containerPort: 7946
              name: http-memberlist
              protocol: TCP
            - containerPort: 3100
              name: http-metrics

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /conf
              name: config
            - mountPath: /var/tempo
              name: data
