apiVersion: v1
kind: Service
metadata:
  name: grafana-agent
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent
  ports:
    - name: http-metrics
      port: 80
      targetPort: 80
      protocol: "TCP"
