apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loki-distributed-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: gateway
spec:
  minReplicas: 1
  maxReplicas: {{ .Values.gateway.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loki-distributed-gateway
