---
# Source: mimir-distributed/templates/configmap/runtime.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-distributed-runtime
  namespace: obskit
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
data:
  runtime.yaml: |
    {}
