apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-distributed-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
data:
  config.yaml: |
    activity_tracker:
      filepath: /active-query-tracker/activity.log

    alertmanager:
      enable_api: false
      # data_dir: /data
      # external_url: /alertmanager
      # fallback_config_file: /configs/alertmanager_fallback_config.yaml

    blocks_storage:
      backend: s3
      s3:
        endpoint: {{ .Values.storage.s3.endpoint }}
        secret_access_key: {{ .Values.storage.s3.secret_access_key }}
        access_key_id: {{ .Values.storage.s3.access_key }}
        bucket_name: {{ .Values.storage.s3.bucket }}
      bucket_store:
        chunks_cache:
          backend: memcached
          memcached:
            addresses: dns+mimir-distributed-chunks-cache-headless.{{ .Values.namespace }}.svc.cluster.local:11211
            max_item_size: 1048576
            timeout: 450ms
        index_cache:
          backend: memcached
          memcached:
            addresses: dns+mimir-distributed-index-cache-headless.{{ .Values.namespace }}.svc.cluster.local:11211
            max_item_size: 5242880
        max_chunk_pool_bytes: 12884901888
        metadata_cache:
          backend: memcached
          memcached:
            addresses: dns+mimir-distributed-metadata-cache-headless.{{ .Values.namespace }}.svc.cluster.local:11211
            max_item_size: 1048576
        sync_dir: /data/tsdb-sync
      tsdb:
        dir: /data/tsdb

    compactor:
      compaction_interval: {{ .Values.compactor.compaction_interval }}
      data_dir: /data
      deletion_delay: 2h
      max_closing_blocks_concurrency: 2
      max_opening_blocks_concurrency: 4
      sharding_ring:
        wait_stability_min_duration: 1m
      symbols_flushers_concurrency: 4

    frontend:
      cache_results: true
      parallelize_shardable_queries: true
      scheduler_address: mimir-distributed-query-scheduler-headless.{{ .Values.namespace }}.svc.cluster.local:9095
      results_cache:
        backend: memcached
        memcached:
          addresses: dns+mimir-distributed-results-cache-headless.{{ .Values.namespace }}.svc.cluster.local:11211
          max_item_size: 1048576
          timeout: 500ms

    frontend_worker:
      # frontend_address: mimir-distributed-query-frontend-headless.{{ .Values.namespace }}.svc.cluster.local:9095
      scheduler_address: mimir-distributed-query-scheduler-headless.{{ .Values.namespace }}.svc.cluster.local:9095
      grpc_client_config:
        max_send_msg_size: 419430400

    ingester:
      ring:
        min_ready_duration: 60s
        final_sleep: 0s
        num_tokens: 512
        tokens_file_path: /data/tokens
        unregister_on_shutdown: false
        zone_awareness_enabled: true

    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600

    limits:
      compactor_block_upload_enabled: true
      max_cache_freshness: 10m
      max_query_parallelism: 240

    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: false
      join_members:
      - dns+mimir-distributed-gossip-ring.{{ .Values.namespace }}.svc.cluster.local:7946

    querier:
      query_store_after: 8h
      max_concurrent: 16

    query_scheduler:
      max_outstanding_requests_per_tenant: 800

    ruler:
      enable_api: false
      # alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.mimir-distributed-alertmanager-headless.{{ .Values.namespace }}.svc.cluster.local/alertmanager
      # rule_path: /data

    runtime_config:
      file: /var/mimir/runtime.yaml

    server:
      log_format: {{ .Values.log.format }}
      log_level: {{ .Values.log.level }}
      grpc_server_max_concurrent_streams: 1000
      grpc_server_max_connection_age: 2m
      grpc_server_max_connection_age_grace: 5m
      grpc_server_max_connection_idle: 1m

    store_gateway:
      sharding_ring:
        kvstore:
          prefix: multi-zone/
        tokens_file_path: /data/tokens
        wait_stability_min_duration: 1m
        zone_awareness_enabled: true

    usage_stats:
      enabled: false
      # installation_mode: helm
