apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-distributed-runtime
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
data:
  runtime.yaml: |
    {}
