apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir-distributed
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
