---
# Source: grafana/templates/service/grafana.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: obskit
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
