namespace: obskit

autoscaling: false
minikube: true
persistence: false
selfmonitor: false
setresources: false

log:
  format: logfmt
  level: debug

ingress:
  enable: false
  host: loki.obskit.com

compactor:
  compaction_interval: 5m

distributor:
  maxReplicas: 2

frontend:
  log_queries_longer_than: 2s

gateway:
  maxReplicas: 2

ingester:
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_idle_period: 10m
  chunk_retain_period: 1m
  maxReplicas: 4

limits_config:
  enforce_metric_name: true
  reject_old_samples_max_age: 96h

memberlist:
  max_join_backoff: 2m
  max_join_retries: 20
  min_join_backoff: 10s

querier:
  maxReplicas: 4

query_frontend:
  maxReplicas: 2

query_range:
  max_retries: 3
  results_cache:
    cache:
      embedded_cache:
        ttl: 24h

storage:
  boltdb_shipper:
    cache_ttl: 168h
  s3:
    access_key: <ACCES_KEY>
    secret_access_key: <SECRET_ACCES_KEY>
    endpoint: <ENDPOINT>
    bucket: <BUCKET_NAME>
