namespace: obskit

autoscaling: false
minikube: true
persistence: false
selfmonitor: false
setresources: false

log:
  format: logfmt
  level: debug

ingress:
  enable: false
  host: tempo.obskit.com

compactor:
  compaction_interval: 5m

distributor:
  maxReplicas: 2

gateway:
  maxReplicas: 2

ingester:
  maxReplicas: 4

querier:
  maxReplicas: 4

query_frontend:
  maxReplicas: 2

storage:
  boltdb_shipper:
    cache_ttl: 168h
  s3:
    access_key: <ACCES_KEY>
    secret_access_key: <SECRET_ACCES_KEY>
    endpoint: <ENDPOINT>
    bucket: <BUCKET_NAME>
