---
# Source: tempo-distributed/templates/serviceaccount/tempo.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo-distributed
  namespace: obskit
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
automountServiceAccountToken: false
