---
# Source: loki-distributed/templates/configmap/default.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-distributed-config
  namespace: obskit
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
data:
  config.yaml: |
    auth_enabled: false

    chunk_store_config:
      chunk_cache_config:
        embedded_cache:
          enabled: false
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.loki-distributed-memcached-chunks.obskit.svc.cluster.local
          consistent_hash: true
      max_look_back_period: 0s
      write_dedupe_cache_config:
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.loki-distributed-memcached-index-writes.obskit.svc.cluster.local
          consistent_hash: true

    common:
      compactor_address: loki-distributed-compactor:3100

    compactor:
      compaction_interval: 5m
      shared_store: s3
      working_directory: /var/loki/compactor

    distributor:
      ring:
        kvstore:
          store: memberlist

    frontend:
      compress_responses: true
      log_queries_longer_than: 2s
      scheduler_address: loki-distributed-query-scheduler:9095
      tail_proxy_url: http://loki-distributed-querier:3100

    frontend_worker:
      # frontend_address: loki-distributed-query-frontend:9095
      scheduler_address: loki-distributed-query-scheduler:9095

    ingester:
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_idle_period: 10m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal

    limits_config:
      enforce_metric_name: true
      reject_old_samples_max_age: 96h

    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
      - loki-distributed-memberlist:7946
      max_join_backoff: 2m
      max_join_retries: 20
      min_join_backoff: 10s

    query_range:
      # align_queries_with_step: true
      cache_results: true
      max_retries: 3
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            ttl: 24h

    schema_config:
      configs:
      - from: "2023-01-01"
        index:
          period: 24h
          prefix: index_
        object_store: s3
        schema: v11
        store: boltdb-shipper

    server:
      http_listen_port: 3100
      log_level: debug
      log_format: logfmt

    storage_config:
      aws:
        access_key_id: <ACCES_KEY>
        bucketnames: <BUCKET_NAME>
        endpoint: <ENDPOINT>
        http_config:
          idle_conn_timeout: 90s
          insecure_skip_verify: false
          response_header_timeout: 10s
        insecure: false
        s3forcepathstyle: true
        secret_access_key: <SECRET_ACCES_KEY>
        sse_encryption: false

      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
        index_gateway_client:
          server_address: dns:///loki-distributed-index-gateway:9095
        shared_store: s3

      index_queries_cache_config:
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.loki-distributed-memcached-index-queries.obskit.svc.cluster.local
          consistent_hash: true
