---
# Source: loki-distributed/templates/configmap/gateway.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-distributed-gateway
  namespace: obskit
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: gateway
data:
  nginx.conf: |
    worker_processes  5;
    error_log  /dev/stderr;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;
    }

    http {
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp_path;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;

      proxy_http_version    1.1;

      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
            '"$request" $body_bytes_sent "$http_referer" '
            '"$http_user_agent" "$http_x_forwarded_for"';
      access_log   /dev/stderr  main;

      sendfile     on;
      tcp_nopush   on;
      resolver kube-dns.kube-system.svc.cluster.local;

      server {
        listen             8080;

        location = / {
          return 200 'OK';
          auth_basic off;
          access_log off;
        }

        location = /api/prom/push {
          set $api_prom_push_backend http://loki-distributed-distributor.obskit.svc.cluster.local;
          proxy_pass       $api_prom_push_backend:3100$request_uri;
          proxy_http_version 1.1;
        }

        location = /api/prom/tail {
          set $api_prom_tail_backend http://loki-distributed-querier.obskit.svc.cluster.local;
          proxy_pass       $api_prom_tail_backend:3100$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_http_version 1.1;
        }

        # Ruler
        # location ~ /prometheus/api/v1/alerts.* {
        #   proxy_pass       http://loki-distributed-ruler.obskit.svc.cluster.local:3100$request_uri;
        # }
        # location ~ /prometheus/api/v1/rules.* {
        #   proxy_pass       http://loki-distributed-ruler.obskit.svc.cluster.local:3100$request_uri;
        # }
        # location ~ /api/prom/rules.* {
        #   proxy_pass       http://loki-distributed-ruler.obskit.svc.cluster.local:3100$request_uri;
        # }
        # location ~ /api/prom/alerts.* {
        #   proxy_pass       http://loki-distributed-ruler.obskit.svc.cluster.local:3100$request_uri;
        # }

        location ~ /api/prom/.* {
          set $api_prom_backend http://loki-distributed-query-frontend-headless.obskit.svc.cluster.local;
          proxy_pass       $api_prom_backend:3100$request_uri;
          proxy_http_version 1.1;
        }

        location = /loki/api/v1/push {
          set $loki_api_v1_push_backend http://loki-distributed-distributor.obskit.svc.cluster.local;
          proxy_pass       $loki_api_v1_push_backend:3100$request_uri;
          proxy_http_version 1.1;
        }

        location = /loki/api/v1/tail {
          set $loki_api_v1_tail_backend http://loki-distributed-querier.obskit.svc.cluster.local;
          proxy_pass       $loki_api_v1_tail_backend:3100$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_http_version 1.1;
        }

        location ~ /loki/api/.* {
          set $loki_api_backend http://loki-distributed-query-frontend-headless.obskit.svc.cluster.local;
          proxy_pass       $loki_api_backend:3100$request_uri;
          proxy_http_version 1.1;
        }
      }
    }
