---
# Source: loki-distributed/templates/configmap/runtime.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-distributed-runtime
  namespace: obskit
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
data:
  runtime.yaml: |
    {}
