apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap/default.yaml
- configmap/gateway.yaml
- configmap/runtime.yaml
- serviceaccount/mimir.yaml
{{ if eq .Values.persistence true }}
- storageclass/mimir.yaml
- persistentvolumeclaim/compactor.yaml
- persistentvolumeclaim/ingester.yaml
- persistentvolumeclaim/store-gateway.yaml
{{ end }}
- service/gossip-ring.yaml
- service/metadata-cache-headless.yaml
- statefulset/metadata-cache.yaml
- service/chunks-cache-headless.yaml
- statefulset/chunks-cache.yaml
- service/index-cache-headless.yaml
- statefulset/index-cache.yaml
- service/results-cache-headless.yaml
- statefulset/results-cache.yaml
{{ if eq .Values.minikube false }}
- poddisruptionbudget/ingester.yaml
{{ end }}
- service/ingester-headless.yaml
- service/ingester.yaml
- statefulset/ingester.yaml
- service/distributor-headless.yaml
- service/distributor.yaml
- deployment/distributor.yaml
{{ if eq .Values.minikube false }}
- poddisruptionbudget/store-gateway.yaml
{{ end }}
- service/store-gateway-headless.yaml
- service/store-gateway.yaml
- statefulset/store-gateway.yaml
- service/compactor.yaml
- statefulset/compactor.yaml
- service/querier.yaml
- deployment/querier.yaml
- service/query-scheduler-headless.yaml
- service/query-scheduler.yaml
- deployment/query-scheduler.yaml
- service/query-frontend-headless.yaml
- service/query-frontend.yaml
- deployment/query-frontend.yaml
- service/gateway.yaml
- deployment/gateway.yaml
{{ if eq .Values.ingress.enable true }}
- secret/gateway-tls.yaml
- ingress/gateway.yaml
{{ end }}
{{ if eq .Values.autoscaling true }}
- horizontalpodautoscaler/ingester.yaml
- horizontalpodautoscaler/distributor.yaml
- horizontalpodautoscaler/store-gateway.yaml
- horizontalpodautoscaler/querier.yaml
- horizontalpodautoscaler/query-frontend.yaml
- horizontalpodautoscaler/gateway.yaml
{{ end }}
