---
# Source: mimir-distributed/templates/poddisruptionbudget/ingester.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-distributed-ingester
  namespace: obskit
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: ingester
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir-distributed
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/component: ingester
