---
# Source: mimir-distributed/templates/poddisruptionbudget/store-gateway.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-distributed-store-gateway
  namespace: obskit
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: store-gateway
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir-distributed
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/component: store-gateway
