---
# Source: loki-distributed/templates/statefulset/memcached-index-queries.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-distributed-memcached-index-queries
  namespace: obskit
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/component: memcached-index-queries
spec:
  serviceName: loki-distributed-memcached-index-queries
  replicas: 1
  revisionHistoryLimit: 10
  updateStrategy:
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: loki-distributed
      app.kubernetes.io/instance: loki
      app.kubernetes.io/component: memcached-index-queries
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki-distributed
        app.kubernetes.io/instance: loki
        app.kubernetes.io/component: memcached-index-queries
    spec:
# 
      serviceAccountName: loki-distributed
      securityContext:
        fsGroup: 11211
        runAsGroup: 11211
        runAsNonRoot: true
        runAsUser: 11211
      terminationGracePeriodSeconds: 30
      containers:
        - name: memcached
          image: docker.io/memcached:1.6.17-alpine
          imagePullPolicy: IfNotPresent
          args:
            - -I 32m
          ports:
            - name: http
              containerPort: 11211
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: http
            timeoutSeconds: 1

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
