apiVersion: v1
kind: Service
metadata:
  name: tempo-distributed-distributor
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: distributor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: distributor
  ports:
    - name: http-metrics
      port: 3100
      targetPort: http-metrics
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
