apiVersion: v1
kind: Service
metadata:
  name: tempo-distributed-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: gateway
spec:
  type: {{ ternary "ClusterIP" "LoadBalancer" (eq .Values.ingress.enable true) }}
  selector:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: gateway
  ports:
    - name: http-metrics
      port: 80
      targetPort: http-metrics
      protocol: TCP
