apiVersion: v1
kind: Service
metadata:
  name: tempo-distributed-querier
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: querier
spec:
  selector:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: querier
  ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: 3100
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
