---
# Source: mimir-distributed/templates/horizontalpodautoscaler/store-gateway.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mimir-distributed-store-gateway-zone-a
  namespace: obskit
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: store-gateway
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mimir-distributed-store-gateway-zone-a
---
# Source: mimir-distributed/templates/horizontalpodautoscaler/store-gateway.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mimir-distributed-store-gateway-zone-b
  namespace: obskit
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: store-gateway
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mimir-distributed-store-gateway-zone-b
---
# Source: mimir-distributed/templates/horizontalpodautoscaler/store-gateway.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mimir-distributed-store-gateway-zone-c
  namespace: obskit
  labels:
    app.kubernetes.io/name: mimir-distributed
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: store-gateway
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mimir-distributed-store-gateway-zone-c
