apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo-distributed-ingester
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: ingester
    app.kubernetes.io/part-of: memberlist
spec:
  replicas: 2 # otlp exporter needs at least 2 replicas
  serviceName: tempo-distributed-ingester
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo-distributed
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/component: ingester
  updateStrategy:
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo-distributed
        app.kubernetes.io/instance: tempo
        app.kubernetes.io/component: ingester
        app.kubernetes.io/part-of: memberlist
    spec:
{{ if eq .Values.minikube false }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: tempo-distributed
                    app.kubernetes.io/instance: tempo
                    app.kubernetes.io/component: ingester
                topologyKey: kubernetes.io/hostname
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: tempo-distributed
                    app.kubernetes.io/instance: tempo
                    app.kubernetes.io/component: ingester
                topologyKey: topology.kubernetes.io/zone
{{ end }}
      enableServiceLinks: false
      serviceAccountName: tempo-distributed
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 300
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: tempo-distributed
              app.kubernetes.io/instance: tempo
              app.kubernetes.io/component: ingester
      volumes:
        - name: config
          configMap:
            name: tempo-distributed-config
        - name: data
{{ if eq .Values.persistence false }}
          emptyDir: {}
{{ else }}
          persistentVolumeClaim:
            claimName: tempo-distributed-ingester
{{ end }}
      containers:
        - name: ingester
          image: docker.io/grafana/tempo:1.5.0
          imagePullPolicy: IfNotPresent
          args:
            - -target=ingester
            - -config.file=/conf/config.yaml
            - -mem-ballast-size-mbs=1024
          ports:
            - name: grpc
              containerPort: 9095
            - name: http-memberlist
              containerPort: 7946
            - name: http-metrics
              containerPort: 3100
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 30
            timeoutSeconds: 1
{{ if eq .Values.setresources true }}
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 2
              memory: 4Gi
{{ end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /conf
              name: config
            - mountPath: /var/tempo
              name: data
