apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: default
  labels:
    app: log-generator
spec:
  selector:
    matchLabels:
      app: log-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        imagePullPolicy: Always
        image: gcr.io/google_containers/logs-generator:v0.1.1
        env:
          - name: LOGS_GENERATOR_LINES_TOTAL
            value: "600000"
          - name: LOGS_GENERATOR_DURATION
            value: "60m"
