---
# Source: tempo-distributed/templates/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap/default.yaml
- configmap/gateway.yaml
- serviceaccount/tempo.yaml

- service/gossip-ring.yaml
- service/memcached.yaml
- statefulset/memcached.yaml
- poddisruptionbudget/ingester.yaml
- service/ingester-discovery.yaml
- service/ingester.yaml
- statefulset/ingester.yaml
- service/distributor-discovery.yaml
- service/distributor.yaml
- deployment/distributor.yaml
- service/compactor.yaml
- deployment/compactor.yaml
- service/querier.yaml
- deployment/querier.yaml
- service/query-frontend-discovery.yaml
- service/query-frontend.yaml
- deployment/query-frontend.yaml
- service/gateway.yaml
- deployment/gateway.yaml
