apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "Z2Jwb3RPM1NqTHpweElJdTZ4eHRoWlFtZnYyOXB3MmVEbjYyZEdzRw=="
  ldap-toml: ""
