{{ if eq .Values.persistence true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimir-distributed-compactor
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: mimir-distributed-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
{{ end }}
