---
# Source: grafana/templates/serviceaccount/grafana.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: obskit
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
