apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-distributed-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
data:
  config.yaml: |
    auth_enabled: false

    chunk_store_config:
      chunk_cache_config:
        embedded_cache:
          enabled: false
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.loki-distributed-memcached-chunks.{{ .Values.namespace }}.svc.cluster.local
          consistent_hash: true
      max_look_back_period: 0s
      write_dedupe_cache_config:
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.loki-distributed-memcached-index-writes.{{ .Values.namespace }}.svc.cluster.local
          consistent_hash: true

    common:
      compactor_address: loki-distributed-compactor:3100

    compactor:
      compaction_interval: {{ .Values.compactor.compaction_interval }}
      shared_store: s3
      working_directory: /var/loki/compactor

    distributor:
      ring:
        kvstore:
          store: memberlist

    frontend:
      compress_responses: true
      log_queries_longer_than: {{ .Values.frontend.log_queries_longer_than }}
      scheduler_address: loki-distributed-query-scheduler:9095
      tail_proxy_url: http://loki-distributed-querier:3100

    frontend_worker:
      # frontend_address: loki-distributed-query-frontend:9095
      scheduler_address: loki-distributed-query-scheduler:9095

    ingester:
      chunk_block_size: {{ .Values.ingester.chunk_block_size }}
      chunk_encoding: {{ .Values.ingester.chunk_encoding }}
      chunk_idle_period: {{ .Values.ingester.chunk_idle_period }}
      chunk_retain_period: {{ .Values.ingester.chunk_retain_period }}
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal

    limits_config:
      enforce_metric_name: {{ .Values.limits_config.enforce_metric_name }}
      reject_old_samples_max_age: {{ .Values.limits_config.reject_old_samples_max_age }}

    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
      - loki-distributed-memberlist:7946
      max_join_backoff: {{ .Values.memberlist.max_join_backoff }}
      max_join_retries: {{ .Values.memberlist.max_join_retries }}
      min_join_backoff: {{ .Values.memberlist.min_join_backoff }}

    query_range:
      # align_queries_with_step: true
      cache_results: true
      max_retries: {{ .Values.query_range.max_retries }}
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            ttl: {{ .Values.query_range.results_cache.cache.embedded_cache.ttl }}

    schema_config:
      configs:
      - from: "2023-01-01"
        index:
          period: 24h
          prefix: index_
        object_store: s3
        schema: v11
        store: boltdb-shipper

    server:
      http_listen_port: 3100
      log_level: {{ .Values.log.level }}
      log_format: {{ .Values.log.format }}

    storage_config:
      aws:
        access_key_id: {{ .Values.storage.s3.access_key }}
        bucketnames: {{ .Values.storage.s3.bucket }}
        endpoint: {{ .Values.storage.s3.endpoint }}
        http_config:
          idle_conn_timeout: 90s
          insecure_skip_verify: false
          response_header_timeout: 10s
        insecure: false
        s3forcepathstyle: true
        secret_access_key: {{ .Values.storage.s3.secret_access_key }}
        sse_encryption: false

      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: {{ .Values.storage.boltdb_shipper.cache_ttl }}
        index_gateway_client:
          server_address: dns:///loki-distributed-index-gateway:9095
        shared_store: s3

      index_queries_cache_config:
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.loki-distributed-memcached-index-queries.{{ .Values.namespace }}.svc.cluster.local
          consistent_hash: true

