---
# Source: loki-distributed/templates/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap/default.yaml
- configmap/gateway.yaml
- configmap/runtime.yaml
- serviceaccount/loki.yaml

- service/memberlist.yaml
- service/memcached-chunks.yaml
- statefulset/memcached-chunks.yaml
- service/memcached-index-writes.yaml
- statefulset/memcached-index-writes.yaml
- service/memcached-index-queries.yaml
- statefulset/memcached-index-queries.yaml
- service/ingester-headless.yaml
- service/ingester.yaml
- statefulset/ingester.yaml
- service/distributor.yaml
- deployment/distributor.yaml
- service/compactor.yaml
- deployment/compactor.yaml
- service/querier.yaml
- deployment/querier.yaml

- service/query-scheduler.yaml
- deployment/query-scheduler.yaml
- service/query-frontend-headless.yaml
- service/query-frontend.yaml
- deployment/query-frontend.yaml
- service/index-gateway-headless.yaml
- service/index-gateway.yaml
- statefulset/index-gateway.yaml
- service/gateway.yaml
- deployment/gateway.yaml
